//! Turn a vehicle's model into the shape the game collides and shoots with.
//!
//! A vehicle used to be a box, and then sixteen boxes, and both were guesses at a mesh that was
//! sitting right there. This runs the mesh through an approximate convex decomposition — the same
//! one Avian would run, from the same version of parry — and writes the result out as a table of
//! vertices, so that the game gets the shape without the model: the server has no assets directory
//! and one of the two models may not be redistributed at all.
//!
//! ```text
//! cargo run -p bake_collider -- list  assets/models/warthog.glb
//! cargo run -p bake_collider -- check assets/models/warthog.glb
//! cargo run -p bake_collider -- bake  assets/models/warthog.glb shared/src/vehicle_shape.rs
//! ```
//!
//! `check` is the reason to trust the output: it fires rays at the real triangles and at the
//! candidate shape and reports how far apart they stop, which is exactly the bug this exists to
//! fix — a bullet hole hanging in the air is a shape that stopped the ray early.

mod model;
mod probe;
mod shapes;

use model::ToChassis;

/// Model units to metres for the Warthog: the chassis is 3.8 m long and the model is 2.0 long.
///
/// Taken from `MODEL_LENGTH` and `BUGGY.half_extents.z` in the game, and checked against them by a
/// test there rather than trusted here — see `the_shape_was_baked_with_the_map_the_model_gets`.
const SCALE: f32 = 1.9;
/// Metres the model rises when it becomes a chassis: `MODEL_GROUND * SCALE - BUGGY.ride_height()`.
const LIFT: f32 = -0.219;

fn main() -> std::process::ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let to_chassis = ToChassis { scale: SCALE, lift: LIFT };
    let result = match args.iter().map(String::as_str).collect::<Vec<_>>().as_slice() {
        ["list", path] => list(path, to_chassis),
        ["check", path] => check(path, to_chassis),
        ["bake", path, out] => bake(path, out, to_chassis),
        _ => Err(format!(
            "usage:\n  {0} list  <model.glb>\n  {0} check <model.glb>\n  {0} bake  <model.glb> <out.rs>",
            env!("CARGO_BIN_NAME")
        )),
    };
    match result {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(why) => {
            eprintln!("{why}");
            std::process::ExitCode::FAILURE
        }
    }
}

/// What is in the file, so that the choice of what to leave out can be made by looking.
fn list(path: &str, to_chassis: ToChassis) -> Result<(), String> {
    let (mesh, pieces) = model::load(path, to_chassis)?;
    println!("{path}: {} pieces, in chassis space\n", pieces.len());
    println!("{:<28} {:>8} {:>8}  {:>26}  in body", "node", "verts", "tris", "size (x, y, z)");
    for piece in &pieces {
        let size = piece.high - piece.low;
        println!(
            "{:<28} {:>8} {:>8}  {:>8.3} {:>8.3} {:>8.3}  {}",
            piece.node,
            piece.vertices,
            piece.triangles,
            size.x,
            size.y,
            size.z,
            if piece.wheel { "no (wheel)" } else { "yes" }
        );
    }
    println!("\nbody: {} vertices, {} triangles", mesh.vertices.len(), mesh.triangles.len());
    Ok(())
}

/// Fire the same rays at the real triangles and at each candidate shape, and print the difference.
fn check(path: &str, to_chassis: ToChassis) -> Result<(), String> {
    let (mesh, _) = model::load(path, to_chassis)?;
    let truth = probe::Truth::new(&mesh)?;
    println!("{} triangles, {} rays each\n", mesh.triangles.len(), probe::RAYS);
    println!(
        "{:<26} {:>6} {:>7} {:>8} {:>8} {:>8} {:>8} {:>8}",
        "shape", "parts", "verts", "med cm", "90th cm", "worst cm", ">5cm", "through"
    );
    for candidate in shapes::candidates(&mesh) {
        let score = truth.score(&candidate.hulls);
        println!(
            "{:<26} {:>6} {:>7} {:>7.1} {:>7.1} {:>7.1} {:>7.0}% {:>7.1}%",
            candidate.name,
            candidate.hulls.len(),
            candidate.hulls.iter().map(|hull| hull.len()).sum::<usize>(),
            score.median * 100.0,
            score.ninetieth * 100.0,
            score.worst * 100.0,
            score.hanging * 100.0,
            score.through * 100.0
        );
    }
    Ok(())
}

/// Write the chosen decomposition out as Rust.
fn bake(path: &str, out: &str, to_chassis: ToChassis) -> Result<(), String> {
    let (mesh, _) = model::load(path, to_chassis)?;
    let hulls = shapes::decompose(&mesh, shapes::CHOSEN);
    let truth = probe::Truth::new(&mesh)?;
    let score = truth.score(&hulls);

    let mut text = String::new();
    text.push_str(&format!(
        "//! The shape a vehicle is, as convex hulls in chassis space.\n\
         //!\n\
         //! Generated by `tools/bake_collider` from `{path}` — **do not edit by hand**. Regenerate\n\
         //! it with:\n\
         //!\n\
         //! ```text\n\
         //! cargo run -p bake_collider -- bake {path} {out}\n\
         //! ```\n\
         //!\n\
         //! The model is not in the repository and the server has never seen one, so the shape has\n\
         //! to travel as numbers rather than as an asset. That is the whole reason this file is\n\
         //! generated instead of loaded.\n\
         //!\n\
         //! Fired at from {} directions and compared against the model's own triangles, this shape\n\
         //! stops a shot a median of {:.1} cm short of the bodywork, {:.1} cm at the ninetieth\n\
         //! percentile and {:.1} cm at worst; {:.0} % of hits are more than 5 cm clear of the panel\n\
         //! and {:.1} % pass through a vehicle they visibly hit.\n\n",
        probe::RAYS,
        score.median * 100.0,
        score.ninetieth * 100.0,
        score.worst * 100.0,
        score.hanging * 100.0,
        score.through * 100.0,
    ));
    text.push_str(
        "// Coordinates, not arithmetic: clippy reads a vertex that happens to land on 0.3010 as a\n\
         // fumbled `LOG10_2`, and says so once per vertex that does.\n\
         #![allow(clippy::approx_constant)]\n\n",
    );
    text.push_str(&format!(
        "/// Model units to metres, as this was baked. The game computes the same number from\n\
         /// `MODEL_LENGTH` and `half_extents`, and a test there checks the two agree.\n\
         pub const BUGGY_BAKE_SCALE: f32 = {SCALE:?};\n\
         /// Metres the model's origin rose to become the chassis's, as this was baked.\n\
         pub const BUGGY_BAKE_LIFT: f32 = {LIFT:?};\n\n"
    ));
    text.push_str(
        "/// One convex hull per entry, each a list of vertices in chassis space, metres.\n\
         ///\n\
         /// Wheels are not in here: they turn, steer and travel on their struts, and a body baked\n\
         /// with them in it would be a vehicle sitting on four blocks. Everything else is —\n\
         /// including the roll cage, which the sixteen boxes this replaces had to leave out.\n\
         pub const BUGGY_BODY: &[&[[f32; 3]]] = &[\n",
    );
    for hull in &hulls {
        text.push_str("    &[\n");
        for vertex in hull {
            text.push_str(&format!(
                "        [{:.4}, {:.4}, {:.4}],\n",
                vertex.x, vertex.y, vertex.z
            ));
        }
        text.push_str("    ],\n");
    }
    text.push_str("];\n");

    std::fs::write(out, &text).map_err(|why| format!("{out}: {why}"))?;
    println!(
        "{out}: {} hulls, {} vertices, {} bytes",
        hulls.len(),
        hulls.iter().map(|hull| hull.len()).sum::<usize>(),
        text.len()
    );
    println!(
        "median {:.1} cm, 90th {:.1} cm, worst {:.1} cm, {:.0} % hanging, {:.1} % through",
        score.median * 100.0,
        score.ninetieth * 100.0,
        score.worst * 100.0,
        score.hanging * 100.0,
        score.through * 100.0
    );
    Ok(())
}
